services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: excel-backend
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: excel-frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
