import { ExcelRowSchema, ExcelTableDTO } from '../schemas/excelTable.schema';

/**
 * Maps a single raw Excel row to a validated ExcelTableDTO using Zod.
 *
 * @param {any} row - The raw row object from Excel, typically generated by XLSX.utils.sheet_to_json.
 * @throws {Error} Throws an error if the row does not pass Zod validation, including field-specific error details.
 * @returns {ExcelTableDTO} The validated and typed DTO representing the Excel row.
 */
export const mapRowToDTO = (row: any): ExcelTableDTO => {
  // Parse the raw row with Zod
  const result = ExcelRowSchema.safeParse({
    companyName: String(row['Empresa'] || ''),
    year: Number(row['Ano'] || ''),
    sector: String(row['Setor'] || ''),
    energyConsumption: Number(row['Consumo de Energia (MWh)'] || ''),
    carbonEmissions: Number(row['Emissões de CO2 (toneladas)'] || ''),
  });

  if (!result.success) {
    throw new Error(`Invalid row: ${JSON.stringify(result.error.flatten().fieldErrors)}`);
  }

  return result.data;
};

export const mapRowsToDTOs = (rows: any[]): ExcelTableDTO[] => {
  return rows.map(mapRowToDTO);
};
